name: finalexam
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^5.5.1
  firebase_auth: ^5.3.4
  sqflite: ^2.4.1
  google_fonts: ^6.2.1
  fluttertoast: ^8.2.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
